# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build/Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: next_version
        uses: zwaldowski/semver-release-action@v3
        with:
          dry_run: true
          bump: ${{ â€¦ }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.next_version.outputs.version }}"

#        - name: Bump version and push tag
#          id: nextTag
#          uses: anothrNick/github-tag-action@1.64.0
#          env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#            WITH_V: true
#  
#        - name: echo new tag
#          run: |
#            echo "The next tag version will be: ${{ steps.nextTag.outputs.new_tag }}"
#            echo "${{ steps.nextTag.outputs.new_tag }}" > version.txt
#            ls
#            cat version.txt
  
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
  
      - name: Build
        run: go build -v ./...
  
      - name: Test
        run: go test -v ./...
  